version: '3.8'

services:
  python-app:
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile-python
    ports:
      - "5000:5000"
    volumes:
      - ../scripts:/app

  node-app:
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile-node
    ports:
      - "3000:3000"

  nginx:
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile-nginx
    ports:
      - "8080:80"