version: '3.8'

services:
  web:
    build:
      context: ../dockerfiles
      dockerfile: Dockerfile-python
    ports:
      - "8080:80"
    volumes:
      - ../scripts:/app
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
