# Use official Nginx image
FROM nginx:alpine

# Copy custom Nginx configuration and index page
COPY scripts/nginx.conf /etc/nginx/nginx.conf
COPY scripts/index.html /usr/share/nginx/html/index.html

# Expose HTTP and HTTPS ports
EXPOSE 80 443
